name: 'clang-format Code Formatter'
description: 'Runs check on hypso code'
author: 'sivertba'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
